for-data-providers = [
    "pystac",
    "stac-validator",
    "stactools",
    "stac-check",
    "stac-node-validator",
    "stac-migrate",
    "stac-fields",
    "stac4s",
    "stac-crosswalks",
    "stac-rs",
]
for-developers = [
    "pystac",
    "stac-pydantic",
    "stac-fastapi",
    "stac-fastapi-elasticsearch-opensearch",
    "stac-fastapi-sqlalchemy",
    "stac-fastapi-pgstac",
    "stac-api-validator",
    "titiler-pgstac",
    "stac-geoparquet",
    "stac-task",
    "stac-server",
    "stac-migrate",
    "stac-fields",
    "stac4s",
    "stac-index",
    "pgstac",
    "stac-rs",
]
for-data-users = [
    "pystac",
    "stac-validator",
    "pystac-client",
    "xstac",
    "xpystac",
    "stac-asset",
    "stac-geoparquet",
    "stac-fields",
    "stac4s",
    "stac-index",
    "stac-rs",
    "stac-terminal",
    "stac-layer",
    "qgis-stac-plugin",
]

[categories]
python = [
    "pystac",
    "pystac-client",
    "stac-fastapi",
    "stac-fastapi-pgstac",
    "stac-fastapi-elasticsearch-opensearch",
    "stac-fastapi-sqlalchemy",
    "stactools",
    "stac-geoparquet",
    "stac-pydantic",
    "stac-asset",
    "stac-validator",
    "stac-check",
    "stac-api-validator",
    "stac-task",
    "titiler-pgstac",
    "xpystac",
    "xstac",
]
javascript = [
    "stac-fields",
    "stac-server",
    "stac-node-validator",
    "stac-migrate",
]
other = [
    "stac-index",
    "pgstac",
    "qgis-stac-plugin",
    "stac-rs",
    "stac-layer",
    "stac4s",
    "stac-terminal",
    "stac-crosswalks",
]
